name: Build and Publish Docker Image

on:
  push:
    branches:
      - test
    paths-ignore:
      - 'README.md'
      - deploy/**
      - .github/**
      - .gitignore

jobs:
  build-and-push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: harbor.dev.meshlake.com:8443
          username: ${{ secrets.MESHLAKE_HARBOR_CICD_USERNAME }}
          password: ${{ secrets.MESHLAKE_HARBOR_CICD_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: harbor.dev.meshlake.com:8443/meshlake/smart-mail-web
          tags: |
            type=raw,value=test
            type=ref,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
